# General settings
token: 1234567890:AAAAAAAA_AAAAAAAAAAAAAAAAAAAAAAAAAA
access_token: rwgegwehksfbwiufoqfiuougdefefouwfwuqfouwwvqfouq
status: develop

# Feeds settings
rss: False
vk: False
rss_feeds:
  -  chatid: -000000000000
     channelid: name of channel
     url: ""

vk_feeds:
  -  chatid: -000000000000
     channelid: test

delay: 30

# Path settings
db_path: jdanbot.db
images_path: bot/cache/{image}.jpg
