FROM python:3.8

RUN apt update && apt install sqlite python3-bs4 -f -y

WORKDIR /app

COPY ./requirements.txt .

RUN pip3 install beautifulsoup4
RUN pip3 install aiohttp
RUN pip3 install tghtml
RUN pip3 install pymemeru
RUN pip3 install -r requirements.txt

CMD [ "python", "./bot.py" ]