[tool.poetry]
name = "jdanbot"
version = "4.0.0a4"
description = "Multifunctional Telegram Bot for banning and stuff."
authors = ["Daniel Zakharov <gzdan734@gmail.com>"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.5.0"
art = "^6.2"
beautifulsoup4 = "^4.10.0"
coloredlogs = "^15.0.1"
httpx = "^0.21.3"
lxml = "^5.4.0"
pyduckgo = "^0.2.0"
emoji = "^1.6.1"
deep-translator = "^1.11.4"
distro = "^1.7.0"
humanize = "^4.1.0"
pytimeparse = "^1.1.8"
ffmpeg-python = "^0.2.0"
wikipya = "^4.0.8"
toml = "^0.10.2"
pydantic-settings = "^2.10.0"
pymemeru = "^0.2.2"
fluentogram = "^1.1.6"
shellous = "^0.36.0"
aiopytesseract = "^0.14.0"
tghtml = "1.1.6.post1"
tortoise-orm = "^0.25.1"
pendulum = "^3.0.0"
wikitextparser = "^0.55.13"
wikitexthtml = "^1.2.0"
# asyncpg = "^0.29.0"
async-property = "^0.2.2"
pyquery = "^2.0.0"
markdownify = "^0.12.1"
markdown = "^3.6"
iso639-lang = "^2.2.3"
pydantic-core = "^2.33.2"
legacy-cgi = "^2.6.3"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.16.0"
bandit = "^1.7.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
mypy = "^1.10.0"
ty = "^0.0.1a16"

[tool.pyright]
reportAssignmentType = false
reportOptionalMemberAccess = false

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 70

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
