[project]
name = "jdanbot"
version = "4.0.0.b1"
description = "Multifunctional Telegram Bot for banning and stuff."
authors = [
  { name = "Daniel Zakharov", email = "gzdan734@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "aiogram>=3.26.0",
  "art>=6.2",
  "beautifulsoup4>=4.14.2",
  "lxml>=6.0.0",
  "pyduckgo",
  "emoji>=1.6.1",
  "distro>=1.7.0",
  "humanize>=4.1.0",
  "pytimeparse2>=1.7.1",
  "python-ffmpeg>=2.0.12",
  "pymemeru",
  "shellous>=0.36.0",
  "aiopytesseract>=0.14.0",
  "tghtml>=1.2.0",
  "pyquery>=2.0.1",
  "iso639-lang>=2.2.3",
  "async-property>=0.2.2",
  "bleach>=6.3.0",
  "whenever>=0.9.5",
  "rich>=14.3.2",
  "wikipya",
  "msgspec[toml]>=0.20.0",
  "aiosql>=15.0",
  "aiosqlite>=0.22.1",
]

[dependency-groups]
dev = [
  "deptry>=0.24.0",
  "faker>=35.0.0",
  "pytest-asyncio>=0.25.2",
  "pytest-sugar>=1.0.0",
  "pytest>=8.3.4",
]

[tool.pyright]
reportUnusedCallResult = false

[tool.pytest.ini_options]
addopts = "-p no:warnings"
norecursedirs = ".svn _build tmp*"
testpaths = "tests"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
line-length = 60

[tool.ruff.lint]
extend-select = [
  "F",      # pyflakes
  "I",      # isort
  "FURB",   # refurb
]

[tool.uv.sources]
wikipya = { git = "https://github.com/jdan735/wikipya", branch = "dev" }
pyduckgo = { git = "https://github.com/jdan735/pyduckgo" }
pymemeru = { git = "https://github.com/jdan735/pymemeru" }

[tool.uv]
default-groups = []
