boikot = "Вы распространили информацию о бойкоте, если вы бойкотировали, то к вам приедут с паяльником"
apple = "Вы распространили информацию о яблоке, если вы яблочник, то к вам приедут с паяльником"

welcome = [
  "Поляк",
  "Джон",
  "Александр Гомель",
  "Иван",
  "УберКац",
  "Яблочник",
  "Электрическая Говноварка",
  "Кацебот",
  "Кацекот",
  "Кац",
  "Яшин",
  "Варламов",
  "Ждан",
  "Двачер",
  "Либертарианец",
]

jdan_welcome = ["jDan", "jBan", "[ДАННЫЕ УДАЛЕНЫ]", "Кайзер", "Кайзур"]

why_list = [
  "Лень",
  "Не знаю",
  "Так исторически сложилось",
  "Так надо",
  "Не скажу",
]

love_words = [
  "бот, спасибо",
  "бот, ты крутой",
  "бот, ты молодец",
  "бот, ты хороший",
  "бот, ты красавчик",
]

[ban_messages]
all = [
  "Вы запостили информацию о бане, если вы не забаненны, то к вам приедут с [ДАННЫЕ ЗАБАНЕННЫ] сроком на 1 минуту",
  "Я из бании прибыть, целебных банов привозить",
  "Бан не плох, особенно на одну минуту",
  "Бан",
  "Анб",
  "Я из Баннии приехать, бан привез :/",
  "Выборы не признаю, но бан да",
  "Помолчи)))",
  "Я приватизировал бан",
  "⚡️⚡️⚡️ Ты получил бан на 1 минуту",
  "‼️‼️‼️ ТЫ ПОЛУЧАЕШЬ БАН)))",
  "Бан бану рознь, но этот лучший",
  "Пора бы за бан и заплатить: /donate",
  "Бань людей — спасай планету",
]

714974074 = "Клоун."
583264555 = "Произошел скам..."
1134491227 = "Произошел скам..."
197416875 = "Где новый стикер?"
795449748 = { text = "Бота фикси! Фикси, фикси, фикси))", sticker = "CAACAgIAAxkBAAIRH1-9ZA59aHjghJzxgkMNayLYOBgeAALCAgAClJlpL1KEXs05fqm3HgQ" }
319384276 = { text = "ДИКтаторов не обслуживаю", sticker = "CAACAgIAAx0CT5lEFgACSRZfRVIL4Tbw5VUWeOMiwuvnzyzgxAAC3wEAApSZaS95fMgpAr5gbhsE" }
